version: '3.8'

services: 
  postgres:
    image: postgres:15-alpine
    container_name: task_managemnt_db
    environment:
      POSTGRES_DB: task_management
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
    ports:
      - "5432:5432"